# LedgerLoop
#
# Only targets that work today are listed. `demo` arrives with the step that
# implements it, rather than sitting here failing.

PY := .venv/Scripts/python.exe

.PHONY: help install test cov lint typecheck check data fixtures ingest eval

help:
	@echo "install    create .venv and install with dev extras"
	@echo "test       run the test suite"
	@echo "cov        run tests with coverage"
	@echo "lint       ruff"
	@echo "typecheck  mypy --strict"
	@echo "check      lint + typecheck + cov"
	@echo "data       generate every split at standard difficulty (gitignored)"
	@echo "fixtures   regenerate the committed 60-order fixture set"
	@echo "ingest     parse and normalise the committed fixture set"
	@echo "eval       regenerate the test split and write EVALUATION.md"

install:
	uv venv --python 3.11
	uv pip install -e ".[dev]"

test:
	$(PY) -m pytest

cov:
	$(PY) -m pytest --cov=ledgerloop --cov-report=term-missing

lint:
	$(PY) -m ruff check .

typecheck:
	$(PY) -m mypy

check: lint typecheck cov

# The evaluated splits never use --ensure-class-coverage: forcing a class into
# them would distort the prevalence they are measured against.
data:
	$(PY) -m ledgerloop.cli generate --split dev         --seed 42
	$(PY) -m ledgerloop.cli generate --split train       --seed 42
	$(PY) -m ledgerloop.cli generate --split calibration --seed 42
	$(PY) -m ledgerloop.cli generate --split test        --seed 42

# The fixture set is the exception: its job is to exercise every code path, not
# to be statistically representative, so class coverage is forced.
fixtures:
	$(PY) -m ledgerloop.cli generate --split dev --difficulty standard --seed 42 \
		--ensure-class-coverage --out data/fixtures/dev-standard-42

# Strict: a fixture that starts quarantining rows should fail, not shrink quietly.
ingest:
	$(PY) -m ledgerloop.cli ingest --data data/fixtures/dev-standard-42 --strict

# PLAN.md §9.4: every reported number comes from `test`, and every number is
# regenerated by one command. The generate step runs first so the report can
# never be produced against a stale dataset.
eval:
	$(PY) -m ledgerloop.cli generate --split test --seed 42
	$(PY) -m ledgerloop.cli eval --data data/generated/test-standard-42 --out EVALUATION.md
