# LedgerLoop
#
# Only targets that work today are listed. `demo` arrives with the step that
# implements it, rather than sitting here failing.

PY := .venv/Scripts/python.exe

.PHONY: help install test cov lint typecheck check data fixtures ingest calibrate eval

help:
	@echo "install    create .venv and install with dev extras"
	@echo "test       run the test suite"
	@echo "cov        run tests with coverage"
	@echo "lint       ruff"
	@echo "typecheck  mypy --strict"
	@echo "check      lint + typecheck + cov"
	@echo "data       generate every split at standard difficulty (gitignored)"
	@echo "fixtures   regenerate the committed 60-order fixture set"
	@echo "ingest     parse and normalise the committed fixture set"
	@echo "calibrate  fit the blender, isotonic and tau_high (train + calibration)"
	@echo "eval       regenerate everything, calibrate, and write EVALUATION.md"

install:
	uv venv --python 3.11
	uv pip install -e ".[dev]"

test:
	$(PY) -m pytest

cov:
	$(PY) -m pytest --cov=ledgerloop --cov-report=term-missing

lint:
	$(PY) -m ruff check .

typecheck:
	$(PY) -m mypy

check: lint typecheck cov

# The evaluated splits never use --ensure-class-coverage: forcing a class into
# them would distort the prevalence they are measured against.
#
# TRAIN_SEEDS / CAL_SEEDS: the blender is fitted across several seeds of each
# split. One 400-order corpus leaves the residual tiers a few dozen decision
# points, which is too few to fit anything against and far too few for a
# precision target of 0.99 to mean anything. The seeds are disjoint between the
# two halves and neither half is ever `test` -- CalibrationProvenance refuses to
# construct a bundle that breaks either rule.
TRAIN_SEEDS := 42 43 44 45 46
CAL_SEEDS   := 47 48 49 50
GEN         := data/generated
TRAIN_DIRS  := $(foreach s,$(TRAIN_SEEDS),$(GEN)/train-standard-$(s))
CAL_DIRS    := $(foreach s,$(CAL_SEEDS),$(GEN)/calibration-standard-$(s))
BUNDLE      := reports/calibration.json

data:
	$(PY) -m ledgerloop.cli generate --split dev  --seed 42
	$(PY) -m ledgerloop.cli generate --split test --seed 42
	$(foreach s,$(TRAIN_SEEDS),$(PY) -m ledgerloop.cli generate --split train --seed $(s);)
	$(foreach s,$(CAL_SEEDS),$(PY) -m ledgerloop.cli generate --split calibration --seed $(s);)

# The fixture set is the exception: its job is to exercise every code path, not
# to be statistically representative, so class coverage is forced.
fixtures:
	$(PY) -m ledgerloop.cli generate --split dev --difficulty standard --seed 42 \
		--ensure-class-coverage --out data/fixtures/dev-standard-42

# Strict: a fixture that starts quarantining rows should fail, not shrink quietly.
ingest:
	$(PY) -m ledgerloop.cli ingest --data data/fixtures/dev-standard-42 --strict

# The fit is a separate command from the report on purpose: the split discipline
# has to be visible in the invocation. Nothing here names `test`.
calibrate: data
	$(PY) -m ledgerloop.cli calibrate \
		--train $(TRAIN_DIRS) \
		--calibration $(CAL_DIRS) \
		--out $(BUNDLE)

# PLAN.md §9.4: every reported number comes from `test`, and every number is
# regenerated by one command. Generation and the fit both run first, so the
# report can never be produced against a stale dataset or a stale model.
eval: calibrate
	$(PY) -m ledgerloop.cli eval \
		--data $(GEN)/test-standard-42 \
		--calibration $(BUNDLE) \
		--out EVALUATION.md
